name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: ./.github/actions/checkout

      - name: Generate Snake Animation
        uses: ./.github/actions/snake
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Show Build Status
        run: git status

      - name: Push to Output Branch
        uses: ./.github/actions/gh-pages
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
